# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_test_data_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='test_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('user_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.test_device')),
            ],
        ),
        migrations.RemoveField(
            model_name='test_data',
            name='user',
        ),
        migrations.AddField(
            model_name='test_data',
            name='burnable_gas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='test_data',
            name='smoke',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='test_data',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='test_data',
            name='data_device_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weixin.test_user'),
            preserve_default=False,
        ),
    ]
