# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_auto_20170127_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_data',
            old_name='burnable_gas',
            new_name='gas',
        ),
    ]
