# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0004_auto_20170129_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_user',
            name='user_device_id',
        ),
        migrations.AddField(
            model_name='test_user',
            name='user_device_id',
            field=models.ManyToManyField(to='weixin.test_device'),
        ),
    ]
