# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0006_auto_20170131_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserAndDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='test_data',
            new_name='data',
        ),
        migrations.RenameModel(
            old_name='test_device',
            new_name='device',
        ),
        migrations.RemoveField(
            model_name='test_user',
            name='user_device_id',
        ),
        migrations.AlterField(
            model_name='data',
            name='data_device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.UserAndDevice'),
        ),
        migrations.DeleteModel(
            name='test_user',
        ),
        migrations.AddField(
            model_name='useranddevice',
            name='UAD_device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.device'),
        ),
        migrations.AddField(
            model_name='useranddevice',
            name='UAD_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.user'),
        ),
        migrations.AlterUniqueTogether(
            name='useranddevice',
            unique_together=set([('UAD_user', 'UAD_device_id')]),
        ),
    ]
