# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170418_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytext', models.TextField()),
            ],
        ),
    ]
