# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 20:04
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mymodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=markdownx.models.MarkdownxField(default=0),
            preserve_default=False,
        ),
    ]
