# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydrone', '0005_auto_20170126_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
