# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydrone', '0006_auto_20170126_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
    ]
