# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydrone', '0007_remove_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
