# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pydrone', '0008_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='test',
            new_name='test1',
        ),
        migrations.AddField(
            model_name='test2',
            name='test2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pydrone.test1'),
        ),
    ]
