# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydrone', '0009_auto_20170126_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test1',
            old_name='test1',
            new_name='test_1',
        ),
        migrations.RenameField(
            model_name='test2',
            old_name='test2',
            new_name='test_2',
        ),
    ]
